IronBody/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IronBody.Models;

namespace IronBody.Controllers
{
    public class AgendaController : Controller
    {
        private IronBody.Models.IronBody db = new Models.IronBody();

        // GET: Agenda
        public ActionResult Index(string Data)
        {
            var agenda = db.Agenda.Include(a => a.Alunos).Include(a => a.Funcionarios);
            
            #region Filtro
            if (!string.IsNullOrEmpty(Data))
            {
                agenda = agenda.Where(c => c.dtInicio == Convert.ToDateTime(Data));
            }
            #endregion

            return View(agenda.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome");
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome");
            return View();
        }

        // POST: Agenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idProfessor,idAluno,dtInicio,atividade,dtFim")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Agenda.Add(agenda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome", agenda.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", agenda.idProfessor);
            return View(agenda);
        }

        // GET: Agenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome", agenda.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", agenda.idProfessor);
            return View(agenda);
        }

        // POST: Agenda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,idProfessor,idAluno,dtInicio,atividade,dtFim")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agenda).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome", agenda.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", agenda.idProfessor);
            return View(agenda);
        }

        // GET: Agenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agenda agenda = db.Agenda.Find(id);
            db.Agenda.Remove(agenda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IronBody/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IronBody.Models;

namespace IronBody.Controllers
{
    public class AlunoController : Controller
    {
        private IronBody.Models.IronBody db = new Models.IronBody();

        // GET: Aluno
        public ActionResult Index(string Alunos,string Instrutor)
        {
            var alunos = db.Alunos.Include(a => a.AvaliacaoFisica).Include(a => a.Funcionarios).Include(a => a.Funcionarios1);
            
            #region Filtro
            if (!string.IsNullOrEmpty(Alunos))
            {
                alunos = alunos.Where(c => c.nome.Contains(Alunos));
            }
            else if (!string.IsNullOrEmpty(Instrutor))
            {
                alunos = alunos.Where(c => c.Funcionarios.nome.Contains(Instrutor));
            }
            #endregion

            return View(alunos.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.idAluno = new SelectList(db.AvaliacaoFisica, "id", "id");
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome");
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome");
            return View();
        }

        // POST: Aluno/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idProfessor,nome,cpf,dtNascimento,cep,estado,cidade,bairro,rua,email,celular")] Alunos alunos)
        {
            if (ModelState.IsValid)
            {
                db.Alunos.Add(alunos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idAluno = new SelectList(db.AvaliacaoFisica, "id", "id", alunos.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", alunos.idProfessor);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", alunos.idProfessor);
            return View(alunos);
        }

        // GET: Aluno/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alunos alunos = db.Alunos.Find(id);
            if (alunos == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAluno = new SelectList(db.AvaliacaoFisica, "id", "id", alunos.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", alunos.idProfessor);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", alunos.idProfessor);
            return View(alunos);
        }

        // POST: Aluno/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Alunos alunos, int id)
        {
            if (ModelState.IsValid)
            {
                alunos.idAluno = id;
                
                db.Entry(alunos).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idAluno = new SelectList(db.AvaliacaoFisica, "id", "id", alunos.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", alunos.idProfessor);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", alunos.idProfessor);
            return View(alunos);
        }

        // GET: Aluno/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alunos alunos = db.Alunos.Find(id);
            if (alunos == null)
            {
                return HttpNotFound();
            }
            return View(alunos);
        }

        // POST: Aluno/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alunos alunos = db.Alunos.Find(id);
            db.Alunos.Remove(alunos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IronBody/Controllers/TreinoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IronBody.Models;

namespace IronBody.Controllers
{
    public class TreinoController : Controller
    {
        private IronBody.Models.IronBody db = new Models.IronBody();

        // GET: Treino
        public ActionResult Index(string Alunos, string Instrutor)
        {
            var treinos = db.Treinos.Include(t => t.Alunos).Include(t => t.Funcionarios);

            #region Filtro
            if (!string.IsNullOrEmpty(Alunos))
            {
                treinos = treinos.Where(c => c.Alunos.nome.Contains(Alunos));
            }
            else if (!string.IsNullOrEmpty(Instrutor))
            {
                treinos = treinos.Where(c => c.Funcionarios.nome.Contains(Instrutor));
            }
            else if (!string.IsNullOrEmpty(Instrutor) && !string.IsNullOrEmpty(Alunos))
            {
                treinos = treinos.Where(c => c.Funcionarios.nome.Contains(Instrutor)).Where(c => c.Alunos.nome.Contains(Alunos));
            }
            #endregion

            return View(treinos.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome");
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome");
            return View();
        }

        // POST: Treino/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idProfessor,idAluno,data,duracao,programa,intervalo,freqTreino,objetivo")] Treinos treinos)
        {
            if (ModelState.IsValid)
            {
                db.Treinos.Add(treinos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome", treinos.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", treinos.idProfessor);
            return View(treinos);
        }

        // GET: Treino/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Treinos treinos = db.Treinos.Find(id);
            if (treinos == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome", treinos.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", treinos.idProfessor);
            return View(treinos);
        }

        // POST: Treino/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,idProfessor,idAluno,data,duracao,programa,intervalo,freqTreino,objetivo")] Treinos treinos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(treinos).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idAluno = new SelectList(db.Alunos, "idAluno", "nome", treinos.idAluno);
            ViewBag.idProfessor = new SelectList(db.Funcionarios, "idFuncionario", "nome", treinos.idProfessor);
            return View(treinos);
        }

        // GET: Treino/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Treinos treinos = db.Treinos.Find(id);
            if (treinos == null)
            {
                return HttpNotFound();
            }
            return View(treinos);
        }

        // POST: Treino/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Treinos treinos = db.Treinos.Find(id);
            db.Treinos.Remove(treinos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IronBody/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
    </div>
    <div>
        <strong>Copyright</strong> Iron Body &copy; 2018
    </div>
</div>

IronBody/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Iron Body | @ViewBag.Title</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
     
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->     
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
    
</head>
<body>

    <!-- Skin configuration box -->
    <!-- @Html.Partial("_SkinConfig") -->

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>
    <!-- End wrapper-->

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

IronBody/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <span class="clear">
                    <span class="block m-t-xs">
                        <strong class="font-bold" style="font-size: 12pt;color: white;">Iron Body</strong>
                    </span>
                    @*<div class="dropdown profile-element">
                            <span>
                                <img alt="image" class="img-circle" src="~/Images/profile_small.jpg" />
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs">
                                        <strong class="font-bold">Usuário</strong>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="@Url.Action("Perfil", "Usuario")">Perfil</a></li>
                                <li class="divider"></li>
                                <li><a href="@Url.Action("Login", "Login")">Logout</a></li>
                            </ul>
                        </div>*@
                    <div class="logo-element">
                        IB
                    </div>
            </li>
            <li>
                <a href="@Url.Action("Index", "Agenda")"><i class="fa fa-calendar"></i> <span class="nav-label" data-i18n="nav.dashboard">Agenda</span></a>
            <li>
                <a href="#"><i class="fa fa-user-o"></i> <span class="nav-label" data-i18n="nav.graphs">Usuários</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Index", "Login")">Login</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Aluno")">Alunos</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Funcionarios")">Funcionários</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="@Url.Action("Index", "Treino")"><i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.dashboard">Treino</span></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "AvaliacaoFisica")"><i class="fa fa-bar-chart-o"></i> <span class="nav-label" data-i18n="nav.layouts">Avaliação Física</span></a>
            </li>

            <li>
                <a href="#"><i class="fa fa-line-chart"></i> <span class="nav-label" data-i18n="nav.graphs">Financeiro</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Index", "ContasPagar")">Contas a Pagar</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "ContasReceber")">Contas a Receber</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

IronBody/Views/Shared/_SkinConfig.cshtml
<div class="theme-config">
    <div class="theme-config-box">
        <div class="spin-icon">
            <i class="fa fa-cogs fa-spin"></i>
        </div>
        <div class="skin-settings">
            <div class="title">Configuration</div>
            <div class="setings-item">
                <span>
                    Collapse menu
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                        <label class="onoffswitch-label" for="collapsemenu">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed sidebar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedsidebar" class="onoffswitch-checkbox" id="fixedsidebar">
                        <label class="onoffswitch-label" for="fixedsidebar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                        <label class="onoffswitch-label" for="fixednavbar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar v.2
                    <br />
                    <small>*Primary layout</small>
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar2" class="onoffswitch-checkbox" id="fixednavbar2">
                        <label class="onoffswitch-label" for="fixednavbar2">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Boxed layout
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                        <label class="onoffswitch-label" for="boxedlayout">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed footer
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedfooter" class="onoffswitch-checkbox" id="fixedfooter">
                        <label class="onoffswitch-label" for="fixedfooter">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="title">Skins</div>
            <div class="setings-item default-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-0">
                        Default
                    </a>
                </span>
            </div>
            <div class="setings-item blue-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-1">
                        Blue light
                    </a>
                </span>
            </div>
            <div class="setings-item yellow-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-3">
                        Yellow/Purple
                    </a>
                </span>
            </div>
            <div class="setings-item ultra-skin">
                <span class="skin-name ">
                    <a target="_blank" href="md_skin/" class="md-skin">
                        Material Design
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

IronBody/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-default " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext" style="color: white;">Bem Vindo ao Sistema Iron Body</span>
            </li>
            @*<li>
                <a href="@Url.Action("Login", "Pages")" style="color: white;">
                    <i class="fa fa-sign-out"></i> Sair
                </a>
            </li>*@
        </ul>
    </nav>  
</div>